from dolfin import *

# Create mesh and define function space
mesh = Mesh("circle.xml.gz")

# Construct the finite element space
P1 = FiniteElement ("Lagrange", mesh . ufl_cell () , 1 )
TH = P1 * P1 * P1
W = FunctionSpace ( mesh , TH )

# Define parameters :
T = ...
dt = ...
delta1 = ...
delta2 = ...
delta3 = ...
alpha = ...
gamma = ...
zeta = ...
L_0 = ...
l = ...
m = ...

# Class representing the intial conditions
class InitialConditions ( UserExpression):
    def eval(self, values , x) :
        values [ 0 ] = ...
        values [ 1 ] = ...
        values [ 2 ] = ...
    def value_shape(self) :
        return (3 ,)

# Define initial condition
indata = InitialConditions(degree = 2)
u0 = Function(W)
u0 = interpolate(indata , W)

# Create bilinear and linear forms
a = ...
L = ...

# Set an output file
...
# Set initial condition
...

# Time - stepping
while t < T :
    # assign u0
    u0 . assign ( u )
    ...
    ...